### ISSUE TITLE
Icon in Database Toolbbar

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/projectgenerator#130]
Draft by @zigertiger

![projectgenerator-icon-databasetoolbar](https://user-images.githubusercontent.com/588407/34607339-65f72bec-f213-11e7-97c7-605c19c2b23b.png)

[projectgenerator-icon.zip](https://github.com/opengisch/projectgenerator/files/1606413/projectgenerator-icon.zip)

**Comment by zigertiger** [comment]
icon created.
[projectgenerator-icon.zip](https://github.com/opengisch/projectgenerator/files/1619175/projectgenerator-icon.zip)

**Comment by m-kuhn** [comment]
Icon is introduced for the plugin itself.

For the toolbar, should this be used for the schemaimport? Should we also have one for import and export?

**Comment by m-kuhn** [comment]
@zigertiger can you have a creative session for import/export functionalities

**Comment by signedav** [comment]
@zigertiger It looks like this. 
![icons_projgen](https://user-images.githubusercontent.com/28384354/45673401-dddbf300-bb2a-11e8-943e-d83058c03a2e.gif)

When your icons are ready and I will add them :slightly_smiling_face:

**Comment by zigertiger** [comment]
comin' right up!
[projectgenerator-offerte-opengisch-20180713.pdf](https://github.com/opengisch/projectgenerator/files/2391988/projectgenerator-offerte-opengisch-20180713.pdf)

**Comment by m-kuhn** [comment]
@zigertiger shall we put the offer into the plugin ;P ?

**Comment by zigertiger** [comment]
haha. wrong pdf

**Comment by signedav** [comment]
Pushed them to the #243 PR.
I like the icons, they are well-made. Still I wonder, if the "subicon" that makes the difference between import/export should be bigger or at least different colored because it's hard to see a difference on this size. 
![projectgenerator icons](https://user-images.githubusercontent.com/28384354/45678096-02899800-bb36-11e8-9436-5d24e325a94d.png)

But IMHO we could go on still with this version because you have the tooltip anyway...

**Comment by m-kuhn** [comment]
@zigertiger the icons are not in the database toolbar. I hope you don't mind.
