### ISSUE TITLE
Delete existing data checkbox doesnt work

### ISSUE THREAD

**Issue by romefi** [opengisch/projectgenerator#220]
We imported an XTF. Then we imported the same xtf again, same settings and with option "delete existing data" set to true (Bestehende Daten in betroffenen Tabellen löschen)

![image](https://user-images.githubusercontent.com/26796989/42451493-bcdf3c5a-8387-11e8-9678-7f1bd1b135e6.png)

After the second import the data was there twice, so the first import hasnt been deleted, even though the option was set to true.

**Comment by m-kuhn** [comment]
CC @gacarrillor

**Comment by gacarrillor** [comment]
This is the command that is being ran by Project Generator v3.0.6 (which is correct):

`java -jar /home/germap/.local/share/QGIS/QGIS3/profiles/default/python/plugins/projectgenerator/libili2db/bin/ili2pg-3.11.2/ili2pg.jar --import --deleteData --dbhost localhost --dbusr postgres --dbpwd postgres --dbdatabase test2 --dbschema test_issue_01 --modeldir /docs/dev/LADM_COL/Catastro_Multiproposito;/docs/dev/LADM_COL/Catastro_Multiproposito/legacy;/docs/dev/LADM_COL/Catastro_Multiproposito/Util;/docs/dev/LADM_COL/ISO --models Catastro_Registro_Nucleo_V2_2_1 --createEnumTabs --createNumChecks --coalesceMultiSurface --createGeomIdx --createFk --createMetaInfo --setupPgExt --smart2Inheritance /docs/borrar/demo_geomatica_andina.xtf`

This is what is ran since v3.0.7 (which is wrong):

`java -jar /home/germap/.local/share/QGIS/QGIS3/profiles/default/python/plugins/projectgenerator/libili2db/bin/ili2pg-3.11.2/ili2pg.jar --coalesceCatalogueRef --createEnumTabs --createNumChecks --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --strokeArcs --beautifyEnumDispName --createUnique --createGeomIdx --createFk --createFkIdx --createMetaInfo --smart1Inheritance --setupPgExt --modeldir /docs/dev/LADM_COL/Catastro_Multiproposito;/docs/dev/LADM_COL/Catastro_Multiproposito/legacy;/docs/dev/LADM_COL/Catastro_Multiproposito/Util;/docs/dev/LADM_COL/ISO --dbhost localhost --dbusr postgres --dbpwd ****** --dbdatabase test2 --dbschema test_issue_01 --models Catastro_Registro_Nucleo_V2_2_1`

Certainly different! The latter doesn't even run an ili2db `import`!!! 

What happened in between?

**Comment by m-kuhn** [comment]
Thanks for the feedback. My first assumption would be that this was a victim of deduplicating code https://github.com/opengisch/projectgenerator/pull/185 I'll have a look.
